country_codes = {'AFG': 'Afghanistan',
 'ALA': 'Åland Islands',
 'ALB': 'Albania',
 'DZA': 'Algeria',
 'ASM': 'American Samoa',
 'AND': 'Andorra',
 'AGO': 'Angola',
 'AIA': 'Anguilla',
 'ATA': 'Antarctica',
 'ATG': 'Antigua and Barbuda',
 'ARG': 'Argentina',
 'ARM': 'Armenia',
 'ABW': 'Aruba',
 'AUS': 'Australia',
 'AUT': 'Austria',
 'AZE': 'Azerbaijan',
 'BHS': 'Bahamas',
 'BHR': 'Bahrain',
 'BGD': 'Bangladesh',
 'BRB': 'Barbados',
 'BLR': 'Belarus',
 'BEL': 'Belgium',
 'BLZ': 'Belize',
 'BEN': 'Benin',
 'BMU': 'Bermuda',
 'BTN': 'Bhutan',
 'BOL': 'Bolivia (Plurinational State of)',
 'BES': 'Bonaire, Sint Eustatius and Saba',
 'BIH': 'Bosnia and Herzegovina',
 'BWA': 'Botswana',
 'BVT': 'Bouvet Island',
 'BRA': 'Brazil',
 'IOT': 'British Indian Ocean Territory',
 'VGB': 'British Virgin Islands',
 'BRN': 'Brunei Darussalam',
 'BGR': 'Bulgaria',
 'BFA': 'Burkina Faso',
 'BDI': 'Burundi',
 'CPV': 'Cabo Verde',
 'KHM': 'Cambodia',
 'CMR': 'Cameroon',
 'CAN': 'Canada',
 'CYM': 'Cayman Islands',
 'CAF': 'Central African Republic',
 'TCD': 'Chad',
 'CHL': 'Chile',
 'CHN': 'China',
 'HKG': 'China, Hong Kong Special Administrative Region',
 'MAC': 'China, Macao Special Administrative Region',
 'CXR': 'Christmas Island',
 'CCK': 'Cocos (Keeling) Islands',
 'COL': 'Colombia',
 'COM': 'Comoros',
 'COG': 'Congo',
 'COK': 'Cook Islands',
 'CRI': 'Costa Rica',
 'CIV': 'Côte d’Ivoire',
 'HRV': 'Croatia',
 'CUB': 'Cuba',
 'CUW': 'Curaçao',
 'CYP': 'Cyprus',
 'CZE': 'Czechia',
 'PRK': "Democratic People's Republic of Korea ",
 'COD': 'Democratic Republic of the Congo',
 'DNK': 'Denmark',
 'DJI': 'Djibouti',
 'DMA': 'Dominica',
 'DOM': 'Dominican Republic',
 'ECU': 'Ecuador',
 'EGY': 'Egypt',
 'SLV': 'El Salvador',
 'GNQ': 'Equatorial Guinea',
 'ERI': 'Eritrea',
 'EST': 'Estonia',
 'SWZ': 'Eswatini',
 'ETH': 'Ethiopia',
 'FLK': 'Falkland Islands (Malvinas)',
 'FRO': 'Faroe Islands',
 'FJI': 'Fiji',
 'FIN': 'Finland',
 'FRA': 'France',
 'GUF': 'French Guiana',
 'PYF': 'French Polynesia',
 'ATF': 'French Southern Territories',
 'GAB': 'Gabon',
 'GMB': 'Gambia',
 'GEO': 'Georgia',
 'DEU': 'Germany',
 'GHA': 'Ghana',
 'GIB': 'Gibraltar',
 'GRC': 'Greece',
 'GRL': 'Greenland',
 'GRD': 'Grenada',
 'GLP': 'Guadeloupe',
 'GUM': 'Guam',
 'GTM': 'Guatemala',
 'GGY': 'Guernsey',
 'GIN': 'Guinea',
 'GNB': 'Guinea-Bissau',
 'GUY': 'Guyana',
 'HTI': 'Haiti',
 'HMD': 'Heard Island and McDonald Islands',
 'VAT': 'Holy See',
 'HND': 'Honduras',
 'HUN': 'Hungary',
 'ISL': 'Iceland',
 'IND': 'India',
 'IDN': 'Indonesia',
 'IRN': 'Iran (Islamic Republic of)',
 'IRQ': 'Iraq',
 'IRL': 'Ireland',
 'IMN': 'Isle of Man',
 'ISR': 'Israel',
 'ITA': 'Italy',
 'JAM': 'Jamaica',
 'JPN': 'Japan',
 'JEY': 'Jersey',
 'JOR': 'Jordan',
 'KAZ': 'Kazakhstan',
 'KEN': 'Kenya',
 'KIR': 'Kiribati',
 'KWT': 'Kuwait',
 'KGZ': 'Kyrgyzstan',
 'LAO': "Lao People's Democratic Republic ",
 'LVA': 'Latvia',
 'LBN': 'Lebanon',
 'LSO': 'Lesotho',
 'LBR': 'Liberia',
 'LBY': 'Libya',
 'LIE': 'Liechtenstein',
 'LTU': 'Lithuania',
 'LUX': 'Luxembourg',
 'MDG': 'Madagascar',
 'MWI': 'Malawi',
 'MYS': 'Malaysia',
 'MDV': 'Maldives',
 'MLI': 'Mali',
 'MLT': 'Malta',
 'MHL': 'Marshall Islands',
 'MTQ': 'Martinique',
 'MRT': 'Mauritania',
 'MUS': 'Mauritius',
 'MYT': 'Mayotte',
 'MEX': 'Mexico',
 'FSM': 'Micronesia (Federated States of)',
 'MCO': 'Monaco',
 'MNG': 'Mongolia',
 'MNE': 'Montenegro',
 'MSR': 'Montserrat',
 'MAR': 'Morocco',
 'MOZ': 'Mozambique',
 'MMR': 'Myanmar',
 'NAM': 'Namibia',
 'NRU': 'Nauru',
 'NPL': 'Nepal',
 'NLD': 'Netherlands (Kingdom of the)',
 'NCL': 'New Caledonia',
 'NZL': 'New Zealand',
 'NIC': 'Nicaragua',
 'NER': 'Niger',
 'NGA': 'Nigeria',
 'NIU': 'Niue',
 'NFK': 'Norfolk Island',
 'MKD': 'North Macedonia',
 'MNP': 'Northern Mariana Islands',
 'NOR': 'Norway',
 'OMN': 'Oman',
 'PAK': 'Pakistan',
 'PLW': 'Palau',
 'PAN': 'Panama',
 'PNG': 'Papua New Guinea',
 'PRY': 'Paraguay',
 'PER': 'Peru',
 'PHL': 'Philippines',
 'PCN': 'Pitcairn',
 'POL': 'Poland',
 'PRT': 'Portugal',
 'PRI': 'Puerto Rico',
 'QAT': 'Qatar',
 'KOR': 'Republic of Korea',
 'MDA': 'Republic of Moldova',
 'REU': 'Réunion',
 'ROU': 'Romania',
 'RUS': 'Russian Federation',
 'RWA': 'Rwanda',
 'BLM': 'Saint Barthélemy',
 'SHN': 'Saint Helena',
 'KNA': 'Saint Kitts and Nevis',
 'LCA': 'Saint Lucia',
 'MAF': 'Saint Martin (French Part)',
 'SPM': 'Saint Pierre and Miquelon',
 'VCT': 'Saint Vincent and the Grenadines',
 'WSM': 'Samoa',
 'SMR': 'San Marino',
 'STP': 'Sao Tome and Principe',
 '': 'Sark',
 'SAU': 'Saudi Arabia',
 'SEN': 'Senegal',
 'SRB': 'Serbia',
 'SYC': 'Seychelles',
 'SLE': 'Sierra Leone',
 'SGP': 'Singapore',
 'SXM': 'Sint Maarten (Dutch part)',
 'SVK': 'Slovakia',
 'SVN': 'Slovenia',
 'SLB': 'Solomon Islands',
 'SOM': 'Somalia',
 'ZAF': 'South Africa',
 'SGS': 'South Georgia and the South Sandwich Islands',
 'SSD': 'South Sudan',
 'ESP': 'Spain',
 'LKA': 'Sri Lanka',
 'PSE': 'State of Palestine',
 'SDN': 'Sudan',
 'SUR': 'Suriname',
 'SJM': 'Svalbard and Jan Mayen Islands',
 'SWE': 'Sweden',
 'CHE': 'Switzerland',
 'SYR': 'Syrian Arab Republic',
 'TJK': 'Tajikistan',
 'THA': 'Thailand',
 'TLS': 'Timor-Leste',
 'TGO': 'Togo',
 'TKL': 'Tokelau',
 'TON': 'Tonga',
 'TTO': 'Trinidad and Tobago',
 'TUN': 'Tunisia',
 'TUR': 'Türkiye',
 'TKM': 'Turkmenistan',
 'TCA': 'Turks and Caicos Islands',
 'TUV': 'Tuvalu',
 'UGA': 'Uganda',
 'UKR': 'Ukraine',
 'ARE': 'United Arab Emirates',
 'GBR': 'United Kingdom of Great Britain and Northern Ireland',
 'TZA': 'United Republic of Tanzania',
 'UMI': 'United States Minor Outlying Islands',
 'USA': 'United States of America',
 'VIR': 'United States Virgin Islands',
 'URY': 'Uruguay',
 'UZB': 'Uzbekistan',
 'VUT': 'Vanuatu',
 'VEN': 'Venezuela (Bolivarian Republic of)',
 'VNM': 'Viet Nam',
 'WLF': 'Wallis and Futuna Islands',
 'ESH': 'Western Sahara',
 'YEM': 'Yemen',
 'ZMB': 'Zambia',
 'ZWE': 'Zimbabwe',

'YUG':'Yugoslavia',
'DDR':'German Democratic Republic',
'CSK':'Czechoslovakia',
'YDYE':'Democratic Yemen',
'USSR':'Union of Soviet Socialist Republics',
'BSSR':'Byelorussian Soviet Socialist Republic',
'EU':'European Union',
'POR':'??'}


regions = {
 'DZA': 'Africa',
 'EGY': 'Africa',
 'LBY': 'Africa',
 'MAR': 'Africa',
 'SDN': 'Africa',
 'TUN': 'Africa',
 'ESH': 'Africa',
 'IOT': 'Africa',
 'BDI': 'Africa',
 'COM': 'Africa',
 'DJI': 'Africa',
 'ERI': 'Africa',
 'ETH': 'Africa',
 'ATF': 'Africa',
 'KEN': 'Africa',
 'MDG': 'Africa',
 'MWI': 'Africa',
 'MUS': 'Africa',
 'MYT': 'Africa',
 'MOZ': 'Africa',
 'REU': 'Africa',
 'RWA': 'Africa',
 'SYC': 'Africa',
 'SOM': 'Africa',
 'SSD': 'Africa',
 'UGA': 'Africa',
 'TZA': 'Africa',
 'ZMB': 'Africa',
 'ZWE': 'Africa',
 'AGO': 'Africa',
 'CMR': 'Africa',
 'CAF': 'Africa',
 'TCD': 'Africa',
 'COG': 'Africa',
 'COD': 'Africa',
 'GNQ': 'Africa',
 'GAB': 'Africa',
 'STP': 'Africa',
 'BWA': 'Africa',
 'SWZ': 'Africa',
 'LSO': 'Africa',
 'NAM': 'Africa',
 'ZAF': 'Africa',
 'BEN': 'Africa',
 'BFA': 'Africa',
 'CPV': 'Africa',
 'CIV': 'Africa',
 'GMB': 'Africa',
 'GHA': 'Africa',
 'GIN': 'Africa',
 'GNB': 'Africa',
 'LBR': 'Africa',
 'MLI': 'Africa',
 'MRT': 'Africa',
 'NER': 'Africa',
 'NGA': 'Africa',
 'SHN': 'Africa',
 'SEN': 'Africa',
 'SLE': 'Africa',
 'TGO': 'Africa',
 'AIA': 'Latin America and the Caribbean',
 'ATG': 'Latin America and the Caribbean',
 'ABW': 'Latin America and the Caribbean',
 'BHS': 'Latin America and the Caribbean',
 'BRB': 'Latin America and the Caribbean',
 'BES': 'Latin America and the Caribbean',
 'VGB': 'Latin America and the Caribbean',
 'CYM': 'Latin America and the Caribbean',
 'CUB': 'Latin America and the Caribbean',
 'CUW': 'Latin America and the Caribbean',
 'DMA': 'Latin America and the Caribbean',
 'DOM': 'Latin America and the Caribbean',
 'GRD': 'Latin America and the Caribbean',
 'GLP': 'Latin America and the Caribbean',
 'HTI': 'Latin America and the Caribbean',
 'JAM': 'Latin America and the Caribbean',
 'MTQ': 'Latin America and the Caribbean',
 'MSR': 'Latin America and the Caribbean',
 'PRI': 'Latin America and the Caribbean',
 'BLM': 'Latin America and the Caribbean',
 'KNA': 'Latin America and the Caribbean',
 'LCA': 'Latin America and the Caribbean',
 'MAF': 'Latin America and the Caribbean',
 'VCT': 'Latin America and the Caribbean',
 'SXM': 'Latin America and the Caribbean',
 'TTO': 'Latin America and the Caribbean',
 'TCA': 'Latin America and the Caribbean',
 'VIR': 'Latin America and the Caribbean',
 'BRB':'Latin America and the Caribbean',
 'BLZ': 'Central America',
 'CRI': 'Central America',
 'SLV': 'Central America',
 'GTM': 'Central America',
 'HND': 'Central America',
 'MEX': 'Central America',
 'NIC': 'Central America',
 'PAN': 'Central America',
 'ARG': 'South America',
 'BOL': 'South America',
 'BVT': 'South America',
 'BRA': 'South America',
 'CHL': 'South America',
 'COL': 'South America',
 'ECU': 'South America',
 'FLK': 'South America',
 'GUF': 'South America',
 'GUY': 'South America',
 'PRY': 'South America',
 'PER': 'South America',
 'SGS': 'South America',
 'SUR': 'South America',
 'URY': 'South America',
 'VEN': 'South America',
 'BMU': 'Northern America',
 'CAN': 'Northern America',
 'GRL': 'Northern America',
 'SPM': 'Northern America',
 'USA': 'Northern America',
 'ATA': 'Northern America',
 'KAZ': 'Asia',
 'KGZ': 'Asia',
 'TJK': 'Asia',
 'TKM': 'Asia',
 'UZB': 'Asia',
 'CHN': 'Asia',
 'HKG': 'Asia',
 'MAC': 'Asia',
 'PRK': 'Asia',
 'JPN': 'Asia',
 'MNG': 'Asia',
 'KOR': 'Asia',
 'BRN': 'Asia',
 'KHM': 'Asia',
 'IDN': 'Asia',
 'LAO': 'Asia',
 'MYS': 'Asia',
 'MMR': 'Asia',
 'PHL': 'Asia',
 'SGP': 'Asia',
 'THA': 'Asia',
 'TLS': 'Asia',
 'VNM': 'Asia',
 'AFG': 'Asia',
 'BGD': 'Asia',
 'BTN': 'Asia',
 'IND': 'Asia',
 'IRN': 'Asia',
 'MDV': 'Asia',
 'NPL': 'Asia',
 'PAK': 'Asia',
 'LKA': 'Asia',
 'ARM': 'Asia',
 'AZE': 'Asia',
 'BHR': 'Asia',
 'CYP': 'Asia',
 'GEO': 'Asia',
 'IRQ': 'Asia',
 'ISR': 'Asia',
 'JOR': 'Asia',
 'KWT': 'Asia',
 'LBN': 'Asia',
 'OMN': 'Asia',
 'QAT': 'Asia',
 'SAU': 'Asia',
 'PSE': 'Asia',
 'SYR': 'Asia',
 'TUR': 'Asia',
 'ARE': 'Asia',
 'YEM': 'Asia',
 'BLR': 'Europe',
 'BGR': 'Europe',
 'CZE': 'Europe',
 'HUN': 'Europe',
 'POL': 'Europe',
 'MDA': 'Europe',
 'ROU': 'Europe',
 'RUS': 'Europe',
'USSR': 'Europe',
'BSSR':'Europe',
 'SVK': 'Europe',
 'UKR': 'Europe',
 'ALA': 'Europe',
 'GGY': 'Europe',
 'JEY': 'Europe',
 'DNK': 'Europe',
 'EST': 'Europe',
 'FRO': 'Europe',
 'FIN': 'Europe',
 'ISL': 'Europe',
 'IRL': 'Europe',
 'IMN': 'Europe',
 'LVA': 'Europe',
 'LTU': 'Europe',
 'NOR': 'Europe',
 'SJM': 'Europe',
 'SWE': 'Europe',
 'GBR': 'Europe',
 'ALB': 'Europe',
 'AND': 'Europe',
 'BIH': 'Europe',
 'HRV': 'Europe',
 'GIB': 'Europe',
 'GRC': 'Europe',
 'VAT': 'Europe',
 'ITA': 'Europe',
 'MLT': 'Europe',
 'MNE': 'Europe',
 'MKD': 'Europe',
 'PRT': 'Europe',
 'SMR': 'Europe',
 'SRB': 'Europe',
 'SVN': 'Europe',
 'ESP': 'Europe',
 'AUT': 'Europe',
 'BEL': 'Europe',
 'FRA': 'Europe',
 'DEU': 'Europe',
 'LIE': 'Europe',
 'LUX': 'Europe',
 'MCO': 'Europe',
 'NLD': 'Europe',
 'CHE': 'Europe',
 'AUS': 'Oceania',
 'CXR': 'Oceania',
 'CCK': 'Oceania',
 'HMD': 'Oceania',
 'NZL': 'Oceania',
 'NFK': 'Oceania',
 'FJI': 'Oceania',
 'NCL': 'Oceania',
 'PNG': 'Oceania',
 'SLB': 'Oceania',
 'VUT': 'Oceania',
 'GUM': 'Oceania',
 'KIR': 'Oceania',
 'MHL': 'Oceania',
 'FSM': 'Oceania',
 'NRU': 'Oceania',
 'MNP': 'Oceania',
 'PLW': 'Oceania',
 'UMI': 'Oceania',
 'ASM': 'Oceania',
 'COK': 'Oceania',
 'PYF': 'Oceania',
 'NIU': 'Oceania',
 'PCN': 'Oceania',
 'WSM': 'Oceania',
 'TKL': 'Oceania',
 'TON': 'Oceania',
 'TUV': 'Oceania',
 'WLF': 'Oceania',
 
 'YUG':'Europe',
'DDR':'Europe',
'CSK':'Europe',
'POR':'Europe',
 'YDYE':'Asia',
 'EU':'Europe'
 }
